# Generated by Django 3.0.3 on 2020-05-25 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rrps_web', '0003_auto_20200525_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='sixthclassadmission',
            name='dateofApp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
